### ISSUE TITLE
CrackMe 0x03

### ISSUE THREAD

**Issue by SysQuirrel** [num1r0/android_crackmes#1]
I found the password but it is in MD5 hash and there is no way to decrypt it...
MD5 hash
ac43bb53262e4edd82c0e82a93c84755
So how are you expecting us to crack it??

**Comment by num1r0** [comment]
Hey Arnesh, glad you found the hash. CrackMe 0x03 was meant to introduce people to a set of tools, including hash cracking tools like hashcat. Make sure you also look into mask attacks ;)
